function(logcoe_ignore_external_warnings target_name)
    if(TARGET ${target_name})
        get_target_property(INCLUDE_DIRS ${target_name} INTERFACE_INCLUDE_DIRECTORIES)
        if(INCLUDE_DIRS)
            set_target_properties(${target_name} PROPERTIES
                INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "${INCLUDE_DIRS}"
            )
            message(STATUS "[logcoe] Ignoring ${target_name} warnings")
        endif()
    else()
        message(WARNING "[logcoe] Target ${target_name} not found")
    endif()
endfunction()

function(logcoe_enable_strict_warnings target_name)
    if(MSVC)
        target_compile_options(${target_name} PRIVATE /W4 /WX)
    else()
        target_compile_options(${target_name} PRIVATE -Werror -Wall -Wextra -Wpedantic)
    endif()
endfunction()

function(logcoe_enable_static_mingw_runtime target_name)
    if(MINGW)
        target_link_options(${target_name} PRIVATE -static)
    endif()
endfunction()
