name: macOS

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        branches: [main]

jobs:
    build-and-test:
        name: ${{ matrix.name }}
        runs-on: macos-latest
        if: github.event.pull_request.draft == false || github.event_name == 'push'
        env:
            CACHE_CMAKE_OPTIONS: '-DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache'
        strategy:
            fail-fast: false
            matrix:
                include:
                    - name: "macOS Clang Debug"
                      compiler: clang
                      cmake-generator: 'Ninja'
                      cmake-options: '-DCMAKE_BUILD_TYPE=Debug'
                      test-target: logcoe_tests

                    - name: "macOS Clang Release"
                      compiler: clang
                      cmake-generator: 'Ninja'
                      cmake-options: '-DCMAKE_BUILD_TYPE=Release'
                      test-target: logcoe_strip_tests

        steps:
        - name: Checkout repository
          uses: actions/checkout@v7

        - name: Setup ccache
          uses: hendrikmuhs/ccache-action@v1.2
          with:
            key: ccache-${{ runner.os }}-${{ matrix.name }}-${{
              hashFiles('cmake/testcoe.cmake', 'tests/CMakeLists.txt') }}
            restore-keys: ccache-${{ runner.os }}-${{ matrix.name }}-

        - name: Configure CMake
          run: |
            cmake -B build -G "${{ matrix.cmake-generator }}" ${{ matrix.cmake-options }} \
                ${{ env.CACHE_CMAKE_OPTIONS }} -DLOGCOE_BUILD_TESTS=ON
          shell: bash

        - name: Build
          run: |
            cmake --build build
          shell: bash
        
        - name: Run tests
          working-directory: build/tests
          run: |
            ./${{ matrix.test-target }}
          shell: bash