name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows",
              os: windows-latest,
              build_type: "Release"
            }
          - {
              name: "Linux",
              os: ubuntu-latest,
              build_type: "Release"
            }
          - {
              name: "macOS",
              os: macos-latest,
              build_type: "Release"
            }

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DLOGCOE_BUILD_TESTS=ON
      
    - name: Build
      run: cmake --build build --config ${{ matrix.config.build_type }}
      
    - name: Run Tests
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ matrix.config.build_type }} --output-on-failure
      
    - name: Install
      run: cmake --install build --prefix install
      
    - name: Create Package
      run: |
        cd install
        zip -r ../logcoe-${{ runner.os }}-${{ matrix.config.build_type }}.zip .
      if: runner.os != 'Windows'
      
    - name: Create Package (Windows)
      run: |
        cd install
        7z a -tzip ../logcoe-${{ runner.os }}-${{ matrix.config.build_type }}.zip .
      if: runner.os == 'Windows'
      
    - name: Upload Package
      uses: actions/upload-artifact@v3
      with:
        name: logcoe-${{ runner.os }}-${{ matrix.config.build_type }}
        path: logcoe-${{ runner.os }}-${{ matrix.config.build_type }}.zip